version: '3.9'

services:

  userService:
    image: kwetter-user-service
    ports: 
      - 5000:5000

  user-db:
    image: user-db
    environment:
        SA_PASSWORD: "Supersecretpassword123"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433