# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - UserService

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/UserService/*.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    displayName: 'Build Service'
    jobs:
    - job: 'Build'
      steps:
      - task: NuGetToolInstaller@1
      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'
          projects: '$(solution)'
          feedsToUse: 'select'
          vstsFeed: '185db493-fd6f-4232-ad1e-262464f79a02'

      - task: VSBuild@1
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

  - stage: 'ImageCreation'
    displayName: 'Create and Store Image'
    jobs: 
    - job: CreateDockerImage
      pool:
          vmImage: 'ubuntu-latest'
      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'dockerhub'
          repository: 'jtvdheijden/kwetter-backend-userservice'
          command: 'buildAndPush'
          Dockerfile: 'DockerfileUserService'
          tags: latest
